apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.ObjectMeta.Name}}
  namespace: {{.ObjectMeta.Namespace}}
  labels:
    {{range $key, $value := .ObjectMeta.Labels}}
    {{$key}}: {{$value}}
    {{end}}
    myapp.my.domain/manager-by: {{.ObjectMeta.UID}}
spec:
  replicas: {{.Spec.Replicas}}
  selector:
    matchLabels:
      {{range $key, $value := .ObjectMeta.Labels}}
      {{$key}}: {{$value}}
      {{end}}
  template:
    metadata:
      labels:
        {{range $key, $value := .ObjectMeta.Labels}}
        {{$key}}: {{$value}}
        {{end}}
    spec:
      containers:
        - name: {{.ObjectMeta.Name}}
          image: {{.Spec.Image}}
          ports:
            - containerPort: {{.Spec.ContainerPort}}